name: imob_auth
description: A new Flutter package project.
version: 0.0.1
homepage:

publish_to: none

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  # Firebase
  firebase_core: 1.4.0
  firebase_auth: 3.0.1
  cloud_firestore: 2.4.0

  # Input Formatter
  mask_text_input_formatter: 2.0.0

  # State Management, DI and Routes
  mobx: 2.0.1
  flutter_mobx: 2.0.0
  flutter_modular: 3.4.0-dev.6

  # Utils
  equatable: 2.0.0
  flutter_svg: 0.22.0

  # Localization
  flutter_localizations:
    sdk: flutter

  imob_core:
    path: ../imob_core

  imob_design_system:
    path: ../imob_design_system

  imob_informacoes_app:
    path: ../imob_informacoes_app

  flutter:
    sdk: flutter

dev_dependencies:
  # Build Runner / Codegen
  build_runner: 2.0.5
  mobx_codegen: 2.0.1+3

  # Tests
  mocktail: 0.1.4

  # Code Style
  flutter_lints: 1.0.4

  flutter_test:
    sdk: flutter


flutter:
  assets:
    - packages/imob_design_system/assets/svgs/logo/logo_imob_telecom.svg
