name: imob_locador
description: Locador - Imob
publish_to: 'none'

version: 0.0.1+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  # Firebase
  firebase_core: 1.4.0
  firebase_auth: 3.0.1

  # State Management, DI and Routes
  mobx: 2.0.1
  flutter_mobx: 2.0.0
  flutter_modular: 3.4.0

  # Network
  dio: 4.0.0

  # Page Indicator (Onboarding)
  smooth_page_indicator: 0.3.0-nullsafety.0

  # View SVGS
  flutter_svg: ^0.22.0

  # Utils
  equatable: 2.0.0

  # Localization
  flutter_localizations:
    sdk: flutter

  imob_design_system:
    path: ./packages/imob_design_system

  imob_core:
    path: ./packages/imob_core

  imob_auth:
    path: ./packages/imob_auth

  imob_informacoes_app:
    path: ./packages/imob_informacoes_app

  flutter:
    sdk: flutter

dev_dependencies:
  # Build Runner / Codegen
  build_runner: 2.0.5
  mobx_codegen: 2.0.1+3

  # Tests
  mocktail: 0.1.4

  # Code Style
  flutter_lints: 1.0.4

  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - packages/imob_design_system/assets/svgs/logo/logo_imob_telecom.svg
    - assets/onboarding/svgs/
    - assets/home/
    - assets/home/svgs/
    - assets/home/pngs/
    - assets/perfil/pngs/

scripts:
  build_apk: flutter build apk --split-per-abi
  build_bundle: flutter build appbundle
  mobx: flutter pub run build_runner build
  mobx_delete: flutter pub run build_runner build --delete-conflicting-outputs
  mobx_watch: flutter pub run build_runner watch
  mobx_clean: flutter pub run build_runner clean
  package_outdated: flutter pub outdated
  test_coverage: flutter test --coverage

